name: Daily Newsletter Summarizer

on:
  schedule:
    # Run daily at 12:01 AM UTC
    - cron: '1 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  summarize-newsletters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GMAIL_CREDENTIALS }}' > credentials.json
        
    - name: Create token file
      run: |
        echo '${{ secrets.GMAIL_TOKEN }}' > token.json
        
    - name: Run newsletter summarizer
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        NEWSLETTER_LABEL: ${{ secrets.NEWSLETTER_LABEL }}
      run: |
        python main.py
        
    - name: Clean up sensitive files
      run: |
        rm -f credentials.json token.json 